title: Welcome to a blog Ryan Lopes
author: Domuserk/RyanLopes
email: impcomercial.87@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This site nothing but is a site presentation using a github pages

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  https://github.com/domuserk

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
